language: python

services:
- docker

install:
- git clone --depth=1 https://github.com/icclab/rosdocked-irlab --branch=master ~/rosdocked-irlab

before_script:
- cd ~/rosdocked-irlab/workspace_included
- ./run-with-dev.sh
- ls
- hostname

script: ./.ci/run_tests.sh

after_script:
- ./.ci/docker_build.sh

#deploy:
#  provider: script
#  script: bash ./.ci/docker_push.sh
#  on:
#    branch: master
