footprint: [[0.40, -0.31], [0.40, 0.31], [-0.40, 0.31], [-0.40, -0.31]]

publish_frequency: 1.0

inflation_layer:
  inflation_radius: 1.0

obstacle_layer:
  obstacle_range: 2.5
  raytrace_range: 3.0
  observation_sources: scan_front scan_rear camera_front
  scan_front:
    data_type: LaserScan
    topic: /scan_front
    marking: true
    clearing: true
    min_obstacle_height: 0.25
    max_obstacle_height: 0.50
  scan_rear:
    data_type: LaserScan
    topic: /scan_rear
    marking: true
    clearing: true
    min_obstacle_height: 0.25
    max_obstacle_height: 0.50
  camera_front:
    data_type: PointCloud2
    topic: /summit_xl/front_rgbd_camera/depth/points
    marking: true
    clearing: true
    min_obstacle_height: 0.02
    max_obstacle_height: 3.0
