max_obstacle_height: 2.0

# Obstacle Cost Shaping (http://wiki.ros.org/costmap_2d/hydro/inflation)
footprint: [[0.40, -0.31], [0.40, 0.31], [-0.40, 0.31], [-0.40, -0.31]]

map_type: voxel

obstacle_layer:
  enabled:              true
  origin_z:             0.0
  z_resolution:         0.1
  z_voxels:             3
  unknown_threshold:    15
  mark_threshold:       0
  combination_method:   0
  track_unknown_space:  true    # true needed for disabling global path planning through unknown space
  obstacle_range: 2.5
  raytrace_range: 3.0
  origin_z: 0.0
  z_resolution: 0.2
  z_voxels: 2
  publish_voxel_map: false
  observation_sources: scan_front scan_rear camera_front
  scan_front:
    data_type: LaserScan
    topic: /scan_front
    marking: true
    clearing: true
    min_obstacle_height: 0.25
    max_obstacle_height: 0.50
  scan_rear:
    data_type: LaserScan
    topic: /scan_rear
    marking: true
    clearing: true
    min_obstacle_height: 0.25
    max_obstacle_height: 0.50
  camera_front:
    data_type: PointCloud2
    topic: /summit_xl/front_rgbd_camera/depth/points
    marking: true
    clearing: true
    min_obstacle_height: 0.02
    max_obstacle_height: 2.0

inflation_layer:
  enabled:             true
  cost_scaling_factor: 10.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:    1.0 # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true

publish_frequency: 1.0
