# description of params http://wiki.ros.org/costmap_2d/hydro/obstacles
max_obstacle_height: 2.0

# Obstacle Cost Shaping (http://wiki.ros.org/costmap_2d/hydro/inflation)
footprint: [[0.35, -0.3], [0.35, 0.3], [-0.35, 0.3], [-0.35, -0.3]]

map_type: voxel # set to 'costmap' if do not want to do 3d ray tracing (no 3d camera)

obstacle_layer:
  enabled:              true

  # voxel costmap plugin
  origin_z: 0.0
  z_resolution: 0.2
  z_voxels: 2
  unknown_threshold:    15
  mark_threshold:       0
  publish_voxel_map:    false   # set to 'true' for debugging

  combination_method: 0         # obstacle layer will overwrite static layer
  track_unknown_space: true     # true needed for disabling global path planning through unknown space
  obstacle_range: 2.5
  raytrace_range: 3.0

  observation_sources: scan_front scan_rear camera_front
  scan_front:
    data_type: LaserScan
    topic: /scan_front
    marking: true
    clearing: true
    min_obstacle_height: 0.25
    max_obstacle_height: 0.50
    inf_is_valid: true # set to true if scan has inf values
  scan_rear:
    data_type: LaserScan
    topic: /scan_rear
    marking: true
    clearing: true
    min_obstacle_height: 0.25
    max_obstacle_height: 0.50
    inf_is_valid: true
  camera_front:
    data_type: PointCloud2
    topic: /summit_xl/front_rgbd_camera/depth/points
    marking: true
    clearing: true
    min_obstacle_height: 0.02
    max_obstacle_height: 2.0

inflation_layer:
  enabled:             true
  cost_scaling_factor: 10.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:    1.0 # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true
