global_costmap:
  global_frame: /summit_xl_map
  robot_base_frame: /summit_xl_base_footprint
  update_frequency: 0.2
  publish_frequency: 0.1
  static_map: true # use external map

  transform_tolerance: 0.5
  # no obstacle layer
  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
