global_costmap:
  global_frame: /summit_xl_map
  robot_base_frame: /summit_xl_base_footprint
  update_frequency: 1.0
  publish_frequency: 0.5
  static_map: true # use external map
  resolution: 0.05 # 0.05
  footprint_padding: 0.0 # helps with passing through narrow passages

  transform_tolerance: 0.5
  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: obstacle_3d_layer,       type: "costmap_2d::VoxelLayer"}
    - {name: obstacle_2d_layer,       type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
