local_costmap:
  global_frame: /summit_xl_odom
  robot_base_frame: /summit_xl_base_footprint
  update_frequency: 5.0
  publish_frequency: 3.0
  static_map: false
  rolling_window: true
  width: 8.0
  height: 8.0
  resolution: 0.025 #0.05
  transform_tolerance: 0.5
  footprint_padding: 0.0 # helps with passing through narrow passages

  plugins:
    - {name: obstacle_layer,      type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
