# Gripper controller
gripper_left_controller:
    type: effort_controllers/JointEffortController
    joint: gripper_finger_joint
    action_monitor_rate: 20
    goal_tolerance: 0.002
    max_effort: 10
    stall_velocity_threshold: 0.041
    stall_timeout: 1.0
    lower: -0.001
    upper: 0.0301
    velocity: 0.041
