#gripper_joint_trajectory_controller:
#  type: position_controllers/JointTrajectoryController
#  joints:
#     - gripper_finger_joint
#  constraints:
#      goal_time: 0.6
#      stopped_velocity_tolerance: 0.05
#      gripper_finger_joint: {trajectory: 0.1, goal: 0.1}
#  stop_trajectory_duration: 0.5
#  state_publish_rate:  25
#  action_monitor_rate: 10
# Gripper controller
#gripper_action_controller:
#  type: position_controllers/GripperActionController
#  joint: gripper_finger_joint
#  action_monitor_rate: 20
#  goal_tolerance: 0.002
#  max_effort: 100
#  stall_velocity_threshold: 0.001
 # stall_timeout: 1.0

# Gripper controller
gripper_left_controller:
    type: effort_controllers/JointEffortController
    joint: gripper_finger_joint
    action_monitor_rate: 20
    goal_tolerance: 0.002
    max_effort: 10
    stall_velocity_threshold: 0.041
    stall_timeout: 1.0
    lower: -0.001
    upper: 0.0301
    velocity: 0.041

gripper_right_controller:
    type: effort_controllers/JointEffortController
    joint: gripper_right_inner_finger_joint
    action_monitor_rate: 20
    goal_tolerance: 0.002
    max_effort: 10
    stall_velocity_threshold: 0.041
    stall_timeout: 1.0
    lower: -0.001
    upper: 0.0301
    velocity: 0.041



