# Settings for ros_control control loop
gripper_hardware_control_loop:
   loop_hz: 125

# Settings for ros_control hardware interface
gripper_hardware_interface:
   joints:
     - gripper_left_finger_base_joint
     - gripper_right_finger_base_joint

#gripper:
gripper_joint_state_controller:
   type: joint_state_controller/JointStateController
   publish_rate: 125  #100


gripper_joint_position_controller: #GripperActionController GripperActionCOntroller is useful only for a one DOF gripper (only one movable finger). It is useless for parallel grippers where you want to actuate both the fingers. You can instead use JointTrajectoryController which does the job well for multiple fingers in the end-effector.
   type: position_controllers/GripperActionController #positition_controllers/GripperActionController #position_controllers/Robotiq2FActionController
   joints: 
     - gripper_left_finger_base_joint
     - gripper_right_finger_base_joint
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      gripper_left_finger_base_joint: {trajectory: 0.1, goal: 0.01}
      gripper_right_finger_base_joint: {trajectory: 0.1, goal: 0.01}
   stop_trajectory_duration: 0.5
   state_publish_rate:  125
   action_monitor_rate: 10

gripper_joint_trajectory_controller:
   type: position_controllers/JointTrajectoryController #positition_controllers/GripperActionController #position_controllers/Robotiq2FActionController
   joints: 
     - gripper_left_finger_base_joint
     - gripper_right_finger_base_joint
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      gripper_left_finger_base_joint: {trajectory: 0.1, goal: 0.01}
      gripper_right_finger_base_joint: {trajectory: 0.1, goal: 0.01}
   stop_trajectory_duration: 0.5
   state_publish_rate:  125
   action_monitor_rate: 10


#   constraints:
#      goal_time: 0.6
#      stopped_velocity_tolerance: 0.05
#      simple_gripper_robotiq_85_left_knuckle_joint: {trajectory: 0.1, goal: 0.1}
#   stop_trajectory_duration: 0.5
#   state_publish_rate:  125
#   action_monitor_rate: 10



#--------------------------------------------------------------

#simple_gripper:
#  type: position_controllers/JointTrajectoryController
#  joints:
#     - simple_gripper_robotiq_85_left_knuckle_joint
#  constraints:
#      goal_time: 0.6
#      stopped_velocity_tolerance: 0.05
#      simple_gripper_robotiq_85_left_knuckle_joint: {trajectory: 0.1, goal: 0.1}
#  stop_trajectory_duration: 0.5
#  state_publish_rate:  25
#  action_monitor_rate: 10
